### ISSUE TITLE
fix: inconsistent card filtering behaviour 

### ISSUE THREAD

**Issue by NipulM** [Statcraftlk/Game-stat-analysis-app#8]
When users filter cards while on a different page within the 'View all cards' section, the filtered cards are not displayed. Instead, a blank page is shown, leading to an inconsistent user experience.

![image](https://github.com/Statcraftlk/Game-stat-analysis-Frontend/assets/125451160/033d2b4c-7697-429e-bd45-0a3923d67ab5)

**Comment by randilt** [comment]
Fixed the issue, 
cause: the current page number is not resetting when the user adds a search input, so it will render an empty page when theres nothing to map through 

fix: reset the page number whenever user updates the search input
